### ISSUE TITLE
Bans kick not shown on web page

### ISSUE THREAD

**Issue by dymas-cz** [yugecin/tsstats-webviewer#4]
Hello. Im having some problems with BAN/Kick sections. In the DB i can see the ban/kick entry but on the web page it wont load. Appache is showing the following error.

`[Mon Nov 16 19:52:58.322562 2020] [php7:error] [pid 4790] [client x.x.x.x:39178] PHP Fatal error:  Uncaught Error: Call to undefined function mb_strlen() in /var/www/ts3/tsstats/funcs.php:199\nStack trace:\n#0 /var/www/ts3/tsstats/funcs.php(231): limitlength('Watch3r', 15)\n#1 /var/www/ts3/tsstats/view_bans.php(35): mkclientlink('je4+Ur9vg4PnGIS...', 'Watch3r', 15)\n#2 /var/www/ts3/tsstats/index.php(72): include('/var/www/ts3/ts...')\n#3 {main}\n  thrown in /var/www/ts3/tsstats/funcs.php on line 199, referer: https://ts3.coreplay.eu/tsstats/?view=kicks
[Mon Nov 16 19:54:23.167837 2020] [php7:error] [pid 10247] [client x.x.x.x:39290] PHP Fatal error:  Uncaught Error: Call to undefined function mb_strlen() in /var/www/ts3/tsstats/funcs.php:199\nStack trace:\n#0 /var/www/ts3/tsstats/funcs.php(231): limitlength('Watch3r', 15)\n#1 /var/www/ts3/tsstats/view_bans.php(35): mkclientlink('je4+Ur9vg4PnGIS...', 'Watch3r', 15)\n#2 /var/www/ts3/tsstats/index.php(72): include('/var/www/ts3/ts...')\n#3 {main}\n  thrown in /var/www/ts3/tsstats/funcs.php on line 199, referer: https://ts3.coreplay.eu/tsstats/?view=client&uid=je4%2BUr9vg4PnGISFNsPSSVe1WXo%3D`

**Comment by yugecin** [comment]
The `mbstring` extension is needed, either enable it in php.ini or recompile php with mbstring support or install the package that your distro has

**Comment by dymas-cz** [comment]
That did the trick, thanks for the pointer.
